# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/arne/Documents/2022-2023/s2/PSE/PSE_Metro_Simulatie

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/arne/Documents/2022-2023/s2/PSE/PSE_Metro_Simulatie

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/arne/Documents/2022-2023/s2/PSE/PSE_Metro_Simulatie/CMakeFiles /mnt/c/Users/arne/Documents/2022-2023/s2/PSE/PSE_Metro_Simulatie//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/arne/Documents/2022-2023/s2/PSE/PSE_Metro_Simulatie/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named testing_tool

# Build rule for target.
testing_tool: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testing_tool
.PHONY : testing_tool

# fast build rule for target.
testing_tool/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/build
.PHONY : testing_tool/fast

#=============================================================================
# Target rules for targets named main_executable

# Build rule for target.
main_executable: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main_executable
.PHONY : main_executable

# fast build rule for target.
main_executable/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/build
.PHONY : main_executable/fast

src/Line.o: src/Line.cpp.o

.PHONY : src/Line.o

# target to build an object file
src/Line.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/src/Line.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/src/Line.cpp.o
.PHONY : src/Line.cpp.o

src/Line.i: src/Line.cpp.i

.PHONY : src/Line.i

# target to preprocess a source file
src/Line.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/src/Line.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/src/Line.cpp.i
.PHONY : src/Line.cpp.i

src/Line.s: src/Line.cpp.s

.PHONY : src/Line.s

# target to generate assembly for a file
src/Line.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/src/Line.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/src/Line.cpp.s
.PHONY : src/Line.cpp.s

src/MetroSimulation.o: src/MetroSimulation.cpp.o

.PHONY : src/MetroSimulation.o

# target to build an object file
src/MetroSimulation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/src/MetroSimulation.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/src/MetroSimulation.cpp.o
.PHONY : src/MetroSimulation.cpp.o

src/MetroSimulation.i: src/MetroSimulation.cpp.i

.PHONY : src/MetroSimulation.i

# target to preprocess a source file
src/MetroSimulation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/src/MetroSimulation.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/src/MetroSimulation.cpp.i
.PHONY : src/MetroSimulation.cpp.i

src/MetroSimulation.s: src/MetroSimulation.cpp.s

.PHONY : src/MetroSimulation.s

# target to generate assembly for a file
src/MetroSimulation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/src/MetroSimulation.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/src/MetroSimulation.cpp.s
.PHONY : src/MetroSimulation.cpp.s

src/MetroXMLParser.o: src/MetroXMLParser.cpp.o

.PHONY : src/MetroXMLParser.o

# target to build an object file
src/MetroXMLParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/src/MetroXMLParser.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/src/MetroXMLParser.cpp.o
.PHONY : src/MetroXMLParser.cpp.o

src/MetroXMLParser.i: src/MetroXMLParser.cpp.i

.PHONY : src/MetroXMLParser.i

# target to preprocess a source file
src/MetroXMLParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/src/MetroXMLParser.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/src/MetroXMLParser.cpp.i
.PHONY : src/MetroXMLParser.cpp.i

src/MetroXMLParser.s: src/MetroXMLParser.cpp.s

.PHONY : src/MetroXMLParser.s

# target to generate assembly for a file
src/MetroXMLParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/src/MetroXMLParser.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/src/MetroXMLParser.cpp.s
.PHONY : src/MetroXMLParser.cpp.s

src/Station.o: src/Station.cpp.o

.PHONY : src/Station.o

# target to build an object file
src/Station.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/src/Station.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/src/Station.cpp.o
.PHONY : src/Station.cpp.o

src/Station.i: src/Station.cpp.i

.PHONY : src/Station.i

# target to preprocess a source file
src/Station.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/src/Station.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/src/Station.cpp.i
.PHONY : src/Station.cpp.i

src/Station.s: src/Station.cpp.s

.PHONY : src/Station.s

# target to generate assembly for a file
src/Station.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/src/Station.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/src/Station.cpp.s
.PHONY : src/Station.cpp.s

src/Track.o: src/Track.cpp.o

.PHONY : src/Track.o

# target to build an object file
src/Track.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/src/Track.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/src/Track.cpp.o
.PHONY : src/Track.cpp.o

src/Track.i: src/Track.cpp.i

.PHONY : src/Track.i

# target to preprocess a source file
src/Track.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/src/Track.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/src/Track.cpp.i
.PHONY : src/Track.cpp.i

src/Track.s: src/Track.cpp.s

.PHONY : src/Track.s

# target to generate assembly for a file
src/Track.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/src/Track.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/src/Track.cpp.s
.PHONY : src/Track.cpp.s

src/Tram.o: src/Tram.cpp.o

.PHONY : src/Tram.o

# target to build an object file
src/Tram.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/src/Tram.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/src/Tram.cpp.o
.PHONY : src/Tram.cpp.o

src/Tram.i: src/Tram.cpp.i

.PHONY : src/Tram.i

# target to preprocess a source file
src/Tram.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/src/Tram.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/src/Tram.cpp.i
.PHONY : src/Tram.cpp.i

src/Tram.s: src/Tram.cpp.s

.PHONY : src/Tram.s

# target to generate assembly for a file
src/Tram.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/src/Tram.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/src/Tram.cpp.s
.PHONY : src/Tram.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

tinyxml/tinystr.o: tinyxml/tinystr.cpp.o

.PHONY : tinyxml/tinystr.o

# target to build an object file
tinyxml/tinystr.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tinyxml/tinystr.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/tinyxml/tinystr.cpp.o
.PHONY : tinyxml/tinystr.cpp.o

tinyxml/tinystr.i: tinyxml/tinystr.cpp.i

.PHONY : tinyxml/tinystr.i

# target to preprocess a source file
tinyxml/tinystr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tinyxml/tinystr.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/tinyxml/tinystr.cpp.i
.PHONY : tinyxml/tinystr.cpp.i

tinyxml/tinystr.s: tinyxml/tinystr.cpp.s

.PHONY : tinyxml/tinystr.s

# target to generate assembly for a file
tinyxml/tinystr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tinyxml/tinystr.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/tinyxml/tinystr.cpp.s
.PHONY : tinyxml/tinystr.cpp.s

tinyxml/tinyxml.o: tinyxml/tinyxml.cpp.o

.PHONY : tinyxml/tinyxml.o

# target to build an object file
tinyxml/tinyxml.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tinyxml/tinyxml.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/tinyxml/tinyxml.cpp.o
.PHONY : tinyxml/tinyxml.cpp.o

tinyxml/tinyxml.i: tinyxml/tinyxml.cpp.i

.PHONY : tinyxml/tinyxml.i

# target to preprocess a source file
tinyxml/tinyxml.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tinyxml/tinyxml.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/tinyxml/tinyxml.cpp.i
.PHONY : tinyxml/tinyxml.cpp.i

tinyxml/tinyxml.s: tinyxml/tinyxml.cpp.s

.PHONY : tinyxml/tinyxml.s

# target to generate assembly for a file
tinyxml/tinyxml.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tinyxml/tinyxml.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/tinyxml/tinyxml.cpp.s
.PHONY : tinyxml/tinyxml.cpp.s

tinyxml/tinyxmlerror.o: tinyxml/tinyxmlerror.cpp.o

.PHONY : tinyxml/tinyxmlerror.o

# target to build an object file
tinyxml/tinyxmlerror.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tinyxml/tinyxmlerror.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/tinyxml/tinyxmlerror.cpp.o
.PHONY : tinyxml/tinyxmlerror.cpp.o

tinyxml/tinyxmlerror.i: tinyxml/tinyxmlerror.cpp.i

.PHONY : tinyxml/tinyxmlerror.i

# target to preprocess a source file
tinyxml/tinyxmlerror.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tinyxml/tinyxmlerror.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/tinyxml/tinyxmlerror.cpp.i
.PHONY : tinyxml/tinyxmlerror.cpp.i

tinyxml/tinyxmlerror.s: tinyxml/tinyxmlerror.cpp.s

.PHONY : tinyxml/tinyxmlerror.s

# target to generate assembly for a file
tinyxml/tinyxmlerror.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tinyxml/tinyxmlerror.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/tinyxml/tinyxmlerror.cpp.s
.PHONY : tinyxml/tinyxmlerror.cpp.s

tinyxml/tinyxmlparser.o: tinyxml/tinyxmlparser.cpp.o

.PHONY : tinyxml/tinyxmlparser.o

# target to build an object file
tinyxml/tinyxmlparser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tinyxml/tinyxmlparser.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/tinyxml/tinyxmlparser.cpp.o
.PHONY : tinyxml/tinyxmlparser.cpp.o

tinyxml/tinyxmlparser.i: tinyxml/tinyxmlparser.cpp.i

.PHONY : tinyxml/tinyxmlparser.i

# target to preprocess a source file
tinyxml/tinyxmlparser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tinyxml/tinyxmlparser.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/tinyxml/tinyxmlparser.cpp.i
.PHONY : tinyxml/tinyxmlparser.cpp.i

tinyxml/tinyxmlparser.s: tinyxml/tinyxmlparser.cpp.s

.PHONY : tinyxml/tinyxmlparser.s

# target to generate assembly for a file
tinyxml/tinyxmlparser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tinyxml/tinyxmlparser.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main_executable.dir/build.make CMakeFiles/main_executable.dir/tinyxml/tinyxmlparser.cpp.s
.PHONY : tinyxml/tinyxmlparser.cpp.s

tst/ParserTest.o: tst/ParserTest.cpp.o

.PHONY : tst/ParserTest.o

# target to build an object file
tst/ParserTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tst/ParserTest.cpp.o
.PHONY : tst/ParserTest.cpp.o

tst/ParserTest.i: tst/ParserTest.cpp.i

.PHONY : tst/ParserTest.i

# target to preprocess a source file
tst/ParserTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tst/ParserTest.cpp.i
.PHONY : tst/ParserTest.cpp.i

tst/ParserTest.s: tst/ParserTest.cpp.s

.PHONY : tst/ParserTest.s

# target to generate assembly for a file
tst/ParserTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tst/ParserTest.cpp.s
.PHONY : tst/ParserTest.cpp.s

tst/main.o: tst/main.cpp.o

.PHONY : tst/main.o

# target to build an object file
tst/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tst/main.cpp.o
.PHONY : tst/main.cpp.o

tst/main.i: tst/main.cpp.i

.PHONY : tst/main.i

# target to preprocess a source file
tst/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tst/main.cpp.i
.PHONY : tst/main.cpp.i

tst/main.s: tst/main.cpp.s

.PHONY : tst/main.s

# target to generate assembly for a file
tst/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testing_tool.dir/build.make CMakeFiles/testing_tool.dir/tst/main.cpp.s
.PHONY : tst/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main_executable"
	@echo "... testing_tool"
	@echo "... src/Line.o"
	@echo "... src/Line.i"
	@echo "... src/Line.s"
	@echo "... src/MetroSimulation.o"
	@echo "... src/MetroSimulation.i"
	@echo "... src/MetroSimulation.s"
	@echo "... src/MetroXMLParser.o"
	@echo "... src/MetroXMLParser.i"
	@echo "... src/MetroXMLParser.s"
	@echo "... src/Station.o"
	@echo "... src/Station.i"
	@echo "... src/Station.s"
	@echo "... src/Track.o"
	@echo "... src/Track.i"
	@echo "... src/Track.s"
	@echo "... src/Tram.o"
	@echo "... src/Tram.i"
	@echo "... src/Tram.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... tinyxml/tinystr.o"
	@echo "... tinyxml/tinystr.i"
	@echo "... tinyxml/tinystr.s"
	@echo "... tinyxml/tinyxml.o"
	@echo "... tinyxml/tinyxml.i"
	@echo "... tinyxml/tinyxml.s"
	@echo "... tinyxml/tinyxmlerror.o"
	@echo "... tinyxml/tinyxmlerror.i"
	@echo "... tinyxml/tinyxmlerror.s"
	@echo "... tinyxml/tinyxmlparser.o"
	@echo "... tinyxml/tinyxmlparser.i"
	@echo "... tinyxml/tinyxmlparser.s"
	@echo "... tst/ParserTest.o"
	@echo "... tst/ParserTest.i"
	@echo "... tst/ParserTest.s"
	@echo "... tst/main.o"
	@echo "... tst/main.i"
	@echo "... tst/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

